# Generated by Django 6.0.5 on 2026-05-30 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='conversacion',
        ),
        migrations.DeleteModel(
            name='Conversacion',
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
